export const ordersVal: any = {
  invoice_number: 'INV-2024-03-27-211715158',
  purchase_order_number: 'PO-2024-03-27-211715158',
  buyer_type: 'group',
  payment_type: 'postpaid',
  payment_term: 30,
  sales_order_date: '2024-03-27T08:39:11Z',
  purchase_request_date: '2024-03-27T08:38:44Z',
  proforma_date: '2024-03-28T08:41:58.000Z',
  invoice_date: '2024-03-28T08:41:58.000Z',
  invoice_on: 7,
  dueAt: '2024-04-27T08:41:58.000Z',
  payment_info: {
    url: null,
    bank_name: 'BNI Virtual Account',
    expired_at: '2025-03-27T14:31:26.636Z',
    bank_account: '8808999978625006',
    mps_invoice_id: null,
    mps_payment_id: null,
    xendit_pm_id: 'pm-5578d63e-00de-412e-9eb7-7e814587aa90',
    payment_gateway_registery: '',
    payment_method: 'BNI',
    payment_gateway: 'xendit',
    bank_info: {
      name: 'BNI Virtual Account',
      code: 'BNI',
      gateway: 'xendit',
      type: 'VIRTUAL_ACCOUNT',
      image:
        'https://smb-padiumkm-images-public-stage.oss-ap-southeast-5.aliyuncs.com/assets/payment/logo/svg/bni-logo.svg',
      instructions: [
        {
          type: 'ATM',
          text: [
            'Masukkan kartu ATM anda',
            'Pilih bahasa',
            'Masukkan PIN ATM anda',
            'Pilih Menu Lainnya',
            'Pilih Transfer',
            'Pilih jenis rekening yang akan anda gunakan (contoh: Dari Rekening Tabungan)',
            ,
            'Pilih Virtual Account Billing',
            'Masukkan Nomor Virtual Account anda: 8808999978625006',
            ,
            'Tagihan yang harus dibayarkan akan muncul pada layar konfirmasi',
            'Konfirmasi, apabila telah sesuai, lanjutkan transaksi',
            'Transaksi Anda telah selesai',
            'Setelah transaksi anda selesai, invoice ini akan diupdate secara otomatis. Proses ini mungkin memakan waktu hingga 5 menit',
          ],
        },
        {
          type: 'iBank',
          text: [
            'Buka situs https://ibank.bni.co.id',
            'Masukkan User ID dan Password',
            'Pilih menu Transfer',
            'Pilih menu Virtual Account Billing',
            'Masukkan Nomor Virtual Account: 8808999978625006',
            ,
            'Lalu pilih rekening debet yang akan digunakan. Kemudian tekan Lanjut',
            'Tagihan yang harus dibayarkan akan muncul pada layar konfirmasi',
            'Masukkan Kode Otentikasi Token',
            'Transaksi Anda telah selesai',
            'Setelah transaksi anda selesai, invoice ini akan diupdate secara otomatis. Proses ini mungkin memakan waktu hingga 5 menit',
          ],
        },
        {
          type: 'mBank',
          text: [
            'Akses BNI Mobile Banking melalui handphone',
            'Masukkan User ID dan Password',
            'Pilih menu Transfer',
            'Pilih menu Virtual Account Billing, lalu pilih rekening debet',
            'Masukkan Nomor Virtual Account anda: 8808999978625006 pada menu Input Baru',
            ,
            'Tagihan yang harus dibayarkan akan muncul pada layar konfirmasi',
            'Konfirmasi transaksi dan masukkan Password Transaksi',
            'Transaksi Anda telah selesai',
            'Setelah transaksi anda selesai, invoice ini akan diupdate secara otomatis. Proses ini mungkin memakan waktu hingga 5 menit',
          ],
        },
        {
          type: 'Bank Lain (ATM)',
          text: [
            'Pilih Menu lain',
            'Pilih Transfer',
            'Pilih dari rekening tabungan',
            'Pilih ke rek. Bank lain',
            'Masukkan kode bank dilanjutkan dengan nomor Virtual Account anda',
            'Input Nominal yang ditagihkan',
            'sebagai Nominal Transfer',
            'Selesai, transaksi berhasil',
          ],
        },
        {
          type: 'Bank Lain (Mobile Banking)',
          text: [
            'Masukan User ID dan Password',
            'Pilih Transfer',
            'Pilih ke rek. Bank lain',
            'Pilih bank tujuan',
            'Masukkan nomor Virtual Account anda',
            'Input Nominal yang ditagihkan sebagai Nominal Transfer',
            'Selesai, transaksi berhasil',
          ],
        },
        {
          type: 'Bank Lain (Internet Banking)',
          text: [
            'Masukan User ID dan Password',
            'Pilih Transfer',
            'Pilih ke rek. Bank lain',
            'Pilih bank tujuan',
            'Masukkan nomor Virtual Account anda',
            'Input Nominal yang ditagihkan sebagai Nominal Transfer',
            'Selesai, transaksi berhasil',
          ],
        },
      ],
    },
  },
  voucher: {
    discount: 0,
    discount_type: null,
    discount_name: null,
    discount_code: null,
  },
  calculation: {
    invoices: [
      {
        invoice_number: 'INV-2024-03-27-211715158',
        status: {
          id: 24,
          slug: 'postpaid-pending-payment',
          name: 'Menunggu Pembayaran',
        },
        seller: {
          name: 'PT. Testing Halah',
          phone_number: '6285711516999',
          address: 'Jalan jalan santai',
          district: 'Bojong Soang',
          city: 'Kab. Bandung',
          province: 'Jawa Barat',
          zipcode: 40288,
          npwp: '123456789012345',
        },
        history: [
          {
            status_id: 2,
            notes: 'Order baru dibuat oleh : Faikar Ammar',
            createdAt: '2024-03-27T01:38:44.641Z',
          },
          {
            status_id: 3,
            notes: 'Pesanan disetujui oleh Laura Hadid',
            createdAt: '2024-03-27T01:39:11.926Z',
          },
          {
            status_id: 5,
            notes: 'Pesanan diproses Penjual.',
            createdAt: '2024-03-27T01:40:19.611Z',
          },
          {
            status_id: 43,
            notes: 'Jasa telah diselesaikan',
            createdAt: '2024-03-27T01:40:44.518Z',
          },
          {
            status_id: 7,
            notes: 'Pesanan telah diterima',
            createdAt: '2024-03-27T01:41:15.536Z',
          },
          {
            status_id: 18,
            notes: 'Tagihan dikirim penjual',
            createdAt: '2024-03-27T01:41:58.975Z',
          },
          {
            status_id: 19,
            notes: 'Tagihan disetujui staff',
            createdAt: '2024-03-27T01:42:15.108Z',
          },
          {
            status_id: 24,
            notes: 'BNI Virtual Account : 8808999978625006',
            createdAt: '2024-03-27T01:42:20.108Z',
          },
          {
            status_id: 24,
            notes: 'Create FPJP: Successfully Create Data.',
            createdAt: '2024-03-27T01:42:22.786Z',
          },
        ],
        type: 'Invoice',
        price_total: 8000000,
        trx_fee: 0,
        payment_total: 8000000,
        total_before_tax: 8000000,
        products: [
          {
            id: '590571',
            order_shipment_id: '438347',
            product_id: '6603adc353fb0b655480b275',
            quantity: 1,
            notes: '',
            price_per_item: 8000000,
            price_total: 8000000,
            price_vendor_per_item: 8000000,
            weight_per_item: 0,
            weight_total: 0,
            free_shipping: false,
            ppn: 0,
            pph_id: '',
            name: 'Jasa < 10jt ; PPN 0 ; PPH 0',
            desc: 'Buyer staff membeli Jasa < 10jt ; PPN 0 ; PPH 0 sampai buyer terima tagihan (status menunggu pembayaran)',
            image:
              'smb-padiumkm-images-public-stage.oss-ap-southeast-5.aliyuncs.com/product/image/27032024/65b84e07a9c743a059c7d95a/6603adc353fb0b655480b275/df422ad0a51a6b23e2ae347afcdaee.jpeg',
            height: '0',
            width: '0',
            length: '0',
            unit: null,
            weight_unit: '',
            brand: null,
            category_node_id: null,
            insurance: 0,
            type: 2,
            createdAt: '2024-03-27T01:38:44.597Z',
            old_id: null,
            ppn_per_item: 0,
            total_after_tax: 8000000,
          },
        ],
        ppn: 0,
        pph: 0,
        discount: {
          name: null,
          code: null,
          type: null,
          value: 0,
        },
        shipping: {
          agency: '',
          agency_name: '',
          method: '',
          method_name: '',
          cost: 0,
          pph: 0,
          ppn: 0,
          insurance: 0,
          discount: 0,
          cost_after_tax: 0,
        },
        pmk58: {
          dpp_ppn: 0,
          ppn: 0,
          dpp_pph22: 0,
          pph22: 0,
        },
      },
    ],
    subtotal: 8000000,
    shipping_cost: 0,
    shipping_discount: 0,
    shipping_insurance: 0,
    ppn: 0,
    ppn_by_buyer: 0,
    pph: 0,
    shipping_pph: 0,
    trx_fee: 0,
    discount: 0,
    grand_total: 800000,
  },
  status: {
    id: 24,
    slug: 'postpaid-pending-payment',
    name: 'Menunggu Pembayaran',
  },
  shipping: {
    agency: '',
    agency_name: '',
    method: '',
    method_name: '',
  },
  seller: {
    phone_number: '6285711516999',
    name: 'PT. Testing Halah',
    address: 'Jalan jalan santai',
    district: 'Bojong Soang',
    city: 'Kab. Bandung',
    province: 'Jawa Barat',
    zipcode: 40288,
    npwp: '123456789012345',
  },
  buyer: {
    profile: {
      name: 'Faikar Ammar',
      phone_number: '0213219674',
    },
    buyer: {
      name: 'PIP',
      bumn: 'PT Pupuk Indonesia',
      type: 'group',
      npwp_address: null,
      npwp_number: '900198981230125',
      address:
        'Jl. Menteng Raya No.27, RT.1/RW.10, Kb. Sirih, Kec. Menteng, Kota Jakarta Pusat, DKI Jakarta',
      district: 'Menteng',
      city: 'Jakarta Pusat',
      province: 'Jakarta',
      zipcode: 1034,
    },
  },
};
